name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Generate Snake Animation
        uses: Platane/snk@v3  # Removed /svg-only to use full functionality
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir -p dist  # Ensure the directory exists
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update Snake Game" || echo "No changes to commit"
          git push
